apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container
          image: dravula/first-image:latest1 # Replace this with your Docker image reference
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
